package page.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import page.Entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 24 21:02:53 CST 2019
     */
    @Delete({
        "delete from user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 24 21:02:53 CST 2019
     */
    @Insert({
        "insert into user (id, mobile, ",
        "password, nick_name, ",
        "picture, sex, province, ",
        "address, education, ",
        "profession, qq, ",
        "last_pay_time, register_type, ",
        "reg_time)",
        "values (#{id,jdbcType=INTEGER}, #{mobile,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{nickName,jdbcType=VARCHAR}, ",
        "#{picture,jdbcType=VARCHAR}, #{sex,jdbcType=INTEGER}, #{province,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{education,jdbcType=INTEGER}, ",
        "#{profession,jdbcType=VARCHAR}, #{qq,jdbcType=VARCHAR}, ",
        "#{lastPayTime,jdbcType=TIMESTAMP}, #{registerType,jdbcType=INTEGER}, ",
        "#{regTime,jdbcType=TIMESTAMP})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 24 21:02:53 CST 2019
     */
    @Select({
        "select",
        "id, mobile, password, nick_name, picture, sex, province, address, education, ",
        "profession, qq, last_pay_time, register_type, reg_time",
        "from user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="education", property="education", jdbcType=JdbcType.INTEGER),
        @Result(column="profession", property="profession", jdbcType=JdbcType.VARCHAR),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_pay_time", property="lastPayTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="register_type", property="registerType", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_time", property="regTime", jdbcType=JdbcType.TIMESTAMP)
    })
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 24 21:02:53 CST 2019
     */
    @Select({
        "select",
        "id, mobile, password, nick_name, picture, sex, province, address, education, ",
        "profession, qq, last_pay_time, register_type, reg_time",
        "from user"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="education", property="education", jdbcType=JdbcType.INTEGER),
        @Result(column="profession", property="profession", jdbcType=JdbcType.VARCHAR),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_pay_time", property="lastPayTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="register_type", property="registerType", jdbcType=JdbcType.INTEGER),
        @Result(column="reg_time", property="regTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Apr 24 21:02:53 CST 2019
     */
    @Update({
        "update user",
        "set mobile = #{mobile,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "picture = #{picture,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "province = #{province,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "education = #{education,jdbcType=INTEGER},",
          "profession = #{profession,jdbcType=VARCHAR},",
          "qq = #{qq,jdbcType=VARCHAR},",
          "last_pay_time = #{lastPayTime,jdbcType=TIMESTAMP},",
          "register_type = #{registerType,jdbcType=INTEGER},",
          "reg_time = #{regTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);
}